#!/bin/bash
find -type f -name "*.gifind -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d '.' -f 1 | rev | LC_ALL=C sort -f | tr '\n' '\0' | xargs -0 -I {} echo {}f" | rev | cut -d "/" -f 1 | cut -d '.' 2- | rev | LC_ALL=C sort -f
