#!/bin/bash
# Display information about subdomains

audit_subdomain() {
    local domain="$1"
    local subdomain="$2"
    
    dns_records=$(dig +short "$subdomain.$domain")
    record_type=$(echo "$dns_records" | awk 'NR==1 { if (/[.0-9]+/) { print "A" } else { print "CNAME" } }')
    echo "The subdomain $subdomain is a $record_type record and points to $dns_records"
}

if [ "$#" == 1 ]
then
  audit_subdomain "$1" "www"
  audit_subdomain "$1" "lb-01"
  audit_subdomain "$1" "web-01"
  audit_subdomain "$1" "web-02"
elif [ "$#" == 2 ]
then
  audit_subdomain "$1" "$2"
fi
