#!/usr/bin/env bash
# Bash script to install nginx and configure it on server

apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
