#!/usr/bin/env bash
# Bash script that configures a server to make server listen to port 80

replacement="server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /usr/share/nginx/html;
	index index.html index.htm;

	server_name localhost;

	location / {
		try_files \$uri \$uri/ =404;
	}
}"

sed -i '/server {/,/}/c\'"$replacement" /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi
