#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=':' read -r username password uid gid info home shell; do
	    echo "The user $username is part of the $gid gang, lives in "/
	    "$homedir and rides $shell. $gid's place is protected by "/
	    "the passcode x, more info about the user here: $description"
done < "/etc/passwd"
